// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {management} from '../models';

export function DeleteTraining(arg1:number):Promise<void>;

export function GetEvidence(arg1:number):Promise<string>;

export function GetTrainings():Promise<Array<management.TrainingDTO>>;

export function SaveTraining(arg1:management.TrainingDTO):Promise<void>;

export function UploadEvidence(arg1:number,arg2:string):Promise<void>;
