// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTraining(arg1) {
  return window['go']['management']['TrainingService']['DeleteTraining'](arg1);
}

export function GetEvidence(arg1) {
  return window['go']['management']['TrainingService']['GetEvidence'](arg1);
}

export function GetTrainings() {
  return window['go']['management']['TrainingService']['GetTrainings']();
}

export function SaveTraining(arg1) {
  return window['go']['management']['TrainingService']['SaveTraining'](arg1);
}

export function UploadEvidence(arg1, arg2) {
  return window['go']['management']['TrainingService']['UploadEvidence'](arg1, arg2);
}
