// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerarRespaldo() {
  return window['go']['system']['MaintenanceService']['GenerarRespaldo']();
}

export function RestaurarRespaldo() {
  return window['go']['system']['MaintenanceService']['RestaurarRespaldo']();
}

export function SetContext(arg1) {
  return window['go']['system']['MaintenanceService']['SetContext'](arg1);
}
