// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardData() {
  return window['go']['dashboard']['DashboardService']['GetDashboardData']();
}

export function SetContext(arg1) {
  return window['go']['dashboard']['DashboardService']['SetContext'](arg1);
}
