// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCita(arg1) {
  return window['go']['welfare']['AgendaService']['DeleteCita'](arg1);
}

export function GetAllCitas() {
  return window['go']['welfare']['AgendaService']['GetAllCitas']();
}

export function GetCitasProximas() {
  return window['go']['welfare']['AgendaService']['GetCitasProximas']();
}

export function SaveCita(arg1) {
  return window['go']['welfare']['AgendaService']['SaveCita'](arg1);
}
