// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {welfare} from '../models';

export function DeleteCita(arg1:number):Promise<void>;

export function GetAllCitas():Promise<Array<welfare.CitaDTO>>;

export function GetCitasProximas():Promise<Array<welfare.CitaDTO>>;

export function SaveCita(arg1:welfare.CitaDTO):Promise<void>;
