// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDisciplineCase(arg1) {
  return window['go']['welfare']['DisciplineService']['DeleteDisciplineCase'](arg1);
}

export function GetDisciplineCases(arg1) {
  return window['go']['welfare']['DisciplineService']['GetDisciplineCases'](arg1);
}

export function GetSignedAct(arg1) {
  return window['go']['welfare']['DisciplineService']['GetSignedAct'](arg1);
}

export function GetViolenceCases(arg1) {
  return window['go']['welfare']['DisciplineService']['GetViolenceCases'](arg1);
}

export function SaveDisciplineCase(arg1) {
  return window['go']['welfare']['DisciplineService']['SaveDisciplineCase'](arg1);
}

export function UploadSignedAct(arg1, arg2) {
  return window['go']['welfare']['DisciplineService']['UploadSignedAct'](arg1, arg2);
}
