// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {welfare} from '../models';

export function DeleteDisciplineCase(arg1:number):Promise<void>;

export function GetDisciplineCases(arg1:number):Promise<Array<welfare.DisciplineCaseDTO>>;

export function GetSignedAct(arg1:number):Promise<string>;

export function GetViolenceCases(arg1:number):Promise<Array<welfare.DisciplineCaseDTO>>;

export function SaveDisciplineCase(arg1:welfare.DisciplineCaseDTO):Promise<void>;

export function UploadSignedAct(arg1:number,arg2:string):Promise<void>;
