// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {welfare} from '../models';

export function AddCohabitant(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function GetEvaluationFile(arg1:number):Promise<string>;

export function GetHealthData(arg1:number):Promise<welfare.HealthDataDTO>;

export function RemoveCohabitant(arg1:number):Promise<void>;

export function SaveHealthData(arg1:welfare.HealthDataDTO):Promise<void>;

export function UploadEvaluationFile(arg1:number,arg2:string):Promise<void>;
