// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCohabitant(arg1, arg2, arg3, arg4) {
  return window['go']['welfare']['HealthService']['AddCohabitant'](arg1, arg2, arg3, arg4);
}

export function GetEvaluationFile(arg1) {
  return window['go']['welfare']['HealthService']['GetEvaluationFile'](arg1);
}

export function GetHealthData(arg1) {
  return window['go']['welfare']['HealthService']['GetHealthData'](arg1);
}

export function RemoveCohabitant(arg1) {
  return window['go']['welfare']['HealthService']['RemoveCohabitant'](arg1);
}

export function SaveHealthData(arg1) {
  return window['go']['welfare']['HealthService']['SaveHealthData'](arg1);
}

export function UploadEvaluationFile(arg1, arg2) {
  return window['go']['welfare']['HealthService']['UploadEvaluationFile'](arg1, arg2);
}
