// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {institution} from '../models';

export function GetInstitution():Promise<institution.Institucion>;

export function GetLogo():Promise<string>;

export function SaveInstitution(arg1:institution.Institucion):Promise<void>;

export function UploadLogo(arg1:string):Promise<string>;
