// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstitution() {
  return window['go']['institution']['InstitutionService']['GetInstitution']();
}

export function GetLogo() {
  return window['go']['institution']['InstitutionService']['GetLogo']();
}

export function SaveInstitution(arg1) {
  return window['go']['institution']['InstitutionService']['SaveInstitution'](arg1);
}

export function UploadLogo(arg1) {
  return window['go']['institution']['InstitutionService']['UploadLogo'](arg1);
}
