// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';
import {context} from '../models';

export function BusquedaGlobal(arg1:string):Promise<Array<search.GlobalSearchResultDTO>>;

export function SetContext(arg1:context.Context):Promise<void>;
