// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BusquedaGlobal(arg1) {
  return window['go']['search']['SearchService']['BusquedaGlobal'](arg1);
}

export function SetContext(arg1) {
  return window['go']['search']['SearchService']['SetContext'](arg1);
}
