// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirUbicacionReporte(arg1) {
  return window['go']['reports']['ReportService']['AbrirUbicacionReporte'](arg1);
}

export function GenerarReporteDocentes() {
  return window['go']['reports']['ReportService']['GenerarReporteDocentes']();
}

export function GenerarReporteInstitucional() {
  return window['go']['reports']['ReportService']['GenerarReporteInstitucional']();
}
