// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reports} from '../models';

export function AbrirUbicacionReporte(arg1:string):Promise<void>;

export function GenerarReporteBitacoraGestionPDF(arg1:string,arg2:string):Promise<string>;

export function GenerarReporteDerivacionesPDF(arg1:string,arg2:string):Promise<string>;

export function GenerarReporteDocentes():Promise<string>;

export function GenerarReporteEstadisticoPDF(arg1:string,arg2:string):Promise<string>;

export function GenerarReporteFichaEstudiantil(arg1:string):Promise<string>;

export function GenerarReporteInstitucional():Promise<string>;

export function GenerarReporteNominaVulnerabilidadPDF(arg1:string):Promise<string>;

export function ObtenerDatosFichaEstudiantil(arg1:string):Promise<reports.FichaEstudiantilDTO>;

export function ObtenerReporteBitacoraGestion(arg1:string,arg2:string):Promise<reports.BitacoraGestionDTO>;

export function ObtenerReporteDerivaciones(arg1:string,arg2:string):Promise<Array<reports.DerivacionDTO>>;

export function ObtenerReporteEstadistico(arg1:string,arg2:string):Promise<reports.ReporteEstadisticoDTO>;

export function ObtenerReporteNominaVulnerabilidad(arg1:string):Promise<Array<reports.NominaVulnerabilidadDTO>>;
