// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeStudentParallel(arg1, arg2) {
  return window['go']['student']['StudentService']['ChangeStudentParallel'](arg1, arg2);
}

export function EnrollExistingStudent(arg1) {
  return window['go']['student']['StudentService']['EnrollExistingStudent'](arg1);
}

export function EnrollNewStudent(arg1) {
  return window['go']['student']['StudentService']['EnrollNewStudent'](arg1);
}

export function ExportStudentsToExcel(arg1, arg2, arg3) {
  return window['go']['student']['StudentService']['ExportStudentsToExcel'](arg1, arg2, arg3);
}

export function GetAlternativeAulas(arg1) {
  return window['go']['student']['StudentService']['GetAlternativeAulas'](arg1);
}

export function GetStudentByCedula(arg1) {
  return window['go']['student']['StudentService']['GetStudentByCedula'](arg1);
}

export function GetStudentProfile(arg1, arg2) {
  return window['go']['student']['StudentService']['GetStudentProfile'](arg1, arg2);
}

export function GetStudents(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['student']['StudentService']['GetStudents'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetWithdrawnStudents(arg1, arg2, arg3, arg4) {
  return window['go']['student']['StudentService']['GetWithdrawnStudents'](arg1, arg2, arg3, arg4);
}

export function UpdateStudentPhoto(arg1, arg2) {
  return window['go']['student']['StudentService']['UpdateStudentPhoto'](arg1, arg2);
}

export function WithdrawStudent(arg1, arg2, arg3) {
  return window['go']['student']['StudentService']['WithdrawStudent'](arg1, arg2, arg3);
}
