// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {student} from '../models';
import {time} from '../models';

export function ChangeStudentParallel(arg1:number,arg2:number):Promise<void>;

export function EnrollExistingStudent(arg1:student.EnrollmentDTO):Promise<void>;

export function EnrollNewStudent(arg1:student.EnrollmentDTO):Promise<void>;

export function ExportStudentsToExcel(arg1:number,arg2:number,arg3:number):Promise<string>;

export function GetAlternativeAulas(arg1:number):Promise<Array<student.AulaOptionDTO>>;

export function GetStudentByCedula(arg1:string):Promise<student.EnrollmentDTO>;

export function GetStudentProfile(arg1:number,arg2:number):Promise<student.StudentProfileDTO>;

export function GetStudents(arg1:number,arg2:number,arg3:number,arg4:string,arg5:number,arg6:number):Promise<student.StudentListResponse>;

export function GetWithdrawnStudents(arg1:number,arg2:string,arg3:number,arg4:number):Promise<student.WithdrawnStudentListResponse>;

export function UpdateStudentPhoto(arg1:number,arg2:string):Promise<void>;

export function WithdrawStudent(arg1:number,arg2:string,arg3:time.Time):Promise<void>;
