// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignMateria(arg1, arg2, arg3) {
  return window['go']['academic']['ClassroomService']['AssignMateria'](arg1, arg2, arg3);
}

export function CreateAula(arg1, arg2, arg3, arg4) {
  return window['go']['academic']['ClassroomService']['CreateAula'](arg1, arg2, arg3, arg4);
}

export function DeleteAula(arg1) {
  return window['go']['academic']['ClassroomService']['DeleteAula'](arg1);
}

export function GetAulasByAnio(arg1) {
  return window['go']['academic']['ClassroomService']['GetAulasByAnio'](arg1);
}

export function GetCargaHoraria(arg1) {
  return window['go']['academic']['ClassroomService']['GetCargaHoraria'](arg1);
}

export function RemoveMateria(arg1) {
  return window['go']['academic']['ClassroomService']['RemoveMateria'](arg1);
}
