// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function AssignMateria(arg1:number,arg2:number,arg3:number):Promise<void>;

export function CreateAula(arg1:number,arg2:number,arg3:number,arg4:any):Promise<void>;

export function DeleteAula(arg1:number):Promise<void>;

export function GetAulasByAnio(arg1:number):Promise<Array<academic.AulaDTO>>;

export function GetCargaHoraria(arg1:number):Promise<Array<academic.CargaHorariaDTO>>;

export function RemoveMateria(arg1:number):Promise<void>;
