// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function CreateCurso(arg1:string,arg2:number):Promise<academic.Curso>;

export function DeleteCurso(arg1:number):Promise<void>;

export function GetCursos():Promise<Array<academic.Curso>>;

export function UpdateCurso(arg1:number,arg2:string,arg3:number):Promise<void>;
