// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCurso(arg1, arg2) {
  return window['go']['academic']['CourseService']['CreateCurso'](arg1, arg2);
}

export function DeleteCurso(arg1) {
  return window['go']['academic']['CourseService']['DeleteCurso'](arg1);
}

export function GetCursos() {
  return window['go']['academic']['CourseService']['GetCursos']();
}

export function UpdateCurso(arg1, arg2, arg3) {
  return window['go']['academic']['CourseService']['UpdateCurso'](arg1, arg2, arg3);
}
