// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarNivel(arg1) {
  return window['go']['academic']['LevelService']['ActualizarNivel'](arg1);
}

export function CrearNivel(arg1) {
  return window['go']['academic']['LevelService']['CrearNivel'](arg1);
}

export function EliminarNivel(arg1) {
  return window['go']['academic']['LevelService']['EliminarNivel'](arg1);
}

export function ListarNiveles() {
  return window['go']['academic']['LevelService']['ListarNiveles']();
}
