// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function ActualizarNivel(arg1:academic.NivelEducativoDTO):Promise<void>;

export function CrearNivel(arg1:academic.NivelEducativoDTO):Promise<void>;

export function EliminarNivel(arg1:number):Promise<void>;

export function ListarNiveles():Promise<Array<academic.NivelEducativoDTO>>;
