// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateParalelo(arg1) {
  return window['go']['academic']['ParallelService']['CreateParalelo'](arg1);
}

export function DeleteParalelo(arg1) {
  return window['go']['academic']['ParallelService']['DeleteParalelo'](arg1);
}

export function GetParalelos() {
  return window['go']['academic']['ParallelService']['GetParalelos']();
}
