// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function CreateParalelo(arg1:string):Promise<academic.Paralelo>;

export function DeleteParalelo(arg1:number):Promise<void>;

export function GetParalelos():Promise<Array<academic.Paralelo>>;
