// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMateria(arg1, arg2) {
  return window['go']['academic']['SubjectService']['CreateMateria'](arg1, arg2);
}

export function GetMaterias() {
  return window['go']['academic']['SubjectService']['GetMaterias']();
}

export function ToggleMateriaState(arg1) {
  return window['go']['academic']['SubjectService']['ToggleMateriaState'](arg1);
}

export function UpdateMateria(arg1, arg2, arg3) {
  return window['go']['academic']['SubjectService']['UpdateMateria'](arg1, arg2, arg3);
}
