// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function CreateMateria(arg1:string,arg2:string):Promise<academic.Materia>;

export function GetMaterias():Promise<Array<academic.Materia>>;

export function ToggleMateriaState(arg1:number):Promise<void>;

export function UpdateMateria(arg1:number,arg2:string,arg3:string):Promise<void>;
