// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function ActualizarMateria(arg1:academic.MateriaDTO):Promise<void>;

export function CrearMateria(arg1:academic.MateriaDTO):Promise<void>;

export function EliminarMateria(arg1:number):Promise<void>;

export function ListarMaterias():Promise<Array<academic.MateriaDTO>>;
