// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarMateria(arg1) {
  return window['go']['academic']['SubjectService']['ActualizarMateria'](arg1);
}

export function CrearMateria(arg1) {
  return window['go']['academic']['SubjectService']['CrearMateria'](arg1);
}

export function EliminarMateria(arg1) {
  return window['go']['academic']['SubjectService']['EliminarMateria'](arg1);
}

export function ListarMaterias() {
  return window['go']['academic']['SubjectService']['ListarMaterias']();
}
