// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function CreateDocente(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<academic.Docente>;

export function GetDocenteHistory(arg1:number):Promise<Array<Record<string, any>>>;

export function GetDocentes(arg1:string):Promise<Array<academic.Docente>>;

export function ToggleDocenteState(arg1:number):Promise<void>;

export function UpdateDocente(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
