// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDocente(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['academic']['TeacherService']['CreateDocente'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDocenteHistory(arg1) {
  return window['go']['academic']['TeacherService']['GetDocenteHistory'](arg1);
}

export function GetDocentes(arg1) {
  return window['go']['academic']['TeacherService']['GetDocentes'](arg1);
}

export function ToggleDocenteState(arg1) {
  return window['go']['academic']['TeacherService']['ToggleDocenteState'](arg1);
}

export function UpdateDocente(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['academic']['TeacherService']['UpdateDocente'](arg1, arg2, arg3, arg4, arg5);
}
