// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAnioLectivo(arg1) {
  return window['go']['academic']['YearService']['ActivateAnioLectivo'](arg1);
}

export function CloneAnioStructure(arg1, arg2) {
  return window['go']['academic']['YearService']['CloneAnioStructure'](arg1, arg2);
}

export function CloseAnioLectivo(arg1) {
  return window['go']['academic']['YearService']['CloseAnioLectivo'](arg1);
}

export function CreateAnioLectivo(arg1, arg2, arg3) {
  return window['go']['academic']['YearService']['CreateAnioLectivo'](arg1, arg2, arg3);
}

export function DeleteAnioLectivo(arg1) {
  return window['go']['academic']['YearService']['DeleteAnioLectivo'](arg1);
}

export function GetActiveSchoolYear() {
  return window['go']['academic']['YearService']['GetActiveSchoolYear']();
}

export function GetAniosLectivos() {
  return window['go']['academic']['YearService']['GetAniosLectivos']();
}

export function UpdateAnioFechas(arg1, arg2, arg3) {
  return window['go']['academic']['YearService']['UpdateAnioFechas'](arg1, arg2, arg3);
}
