// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {academic} from '../models';

export function ActivarPeriodo(arg1:number):Promise<void>;

export function ActualizarPeriodo(arg1:academic.ActualizarPeriodoDTO):Promise<void>;

export function CerrarPeriodo(arg1:number):Promise<void>;

export function CrearPeriodo(arg1:academic.CrearPeriodoDTO):Promise<void>;

export function EliminarPeriodo(arg1:number):Promise<void>;

export function ListarPeriodos():Promise<Array<academic.PeriodoResponseDTO>>;

export function ObtenerPeriodoActivo():Promise<academic.PeriodoResponseDTO>;
