// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivarPeriodo(arg1) {
  return window['go']['academic']['YearService']['ActivarPeriodo'](arg1);
}

export function ActualizarPeriodo(arg1) {
  return window['go']['academic']['YearService']['ActualizarPeriodo'](arg1);
}

export function CerrarPeriodo(arg1) {
  return window['go']['academic']['YearService']['CerrarPeriodo'](arg1);
}

export function CrearPeriodo(arg1) {
  return window['go']['academic']['YearService']['CrearPeriodo'](arg1);
}

export function EliminarPeriodo(arg1) {
  return window['go']['academic']['YearService']['EliminarPeriodo'](arg1);
}

export function ListarPeriodos() {
  return window['go']['academic']['YearService']['ListarPeriodos']();
}

export function ObtenerPeriodoActivo() {
  return window['go']['academic']['YearService']['ObtenerPeriodoActivo']();
}
