// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {academic} from '../models';

export function ActivateAnioLectivo(arg1:number):Promise<void>;

export function CloneAnioStructure(arg1:number,arg2:number):Promise<void>;

export function CloseAnioLectivo(arg1:number):Promise<void>;

export function CreateAnioLectivo(arg1:string,arg2:time.Time,arg3:time.Time):Promise<academic.AnioLectivo>;

export function DeleteAnioLectivo(arg1:number):Promise<void>;

export function GetAniosLectivos():Promise<Array<academic.AnioLectivo>>;

export function UpdateAnioFechas(arg1:number,arg2:time.Time,arg3:time.Time):Promise<void>;
