// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAnioLectivo(arg1) {
  return window['go']['services']['AcademicService']['ActivateAnioLectivo'](arg1);
}

export function CloneAnioStructure(arg1, arg2) {
  return window['go']['services']['AcademicService']['CloneAnioStructure'](arg1, arg2);
}

export function CloseAnioLectivo(arg1) {
  return window['go']['services']['AcademicService']['CloseAnioLectivo'](arg1);
}

export function CreateAnioLectivo(arg1, arg2, arg3) {
  return window['go']['services']['AcademicService']['CreateAnioLectivo'](arg1, arg2, arg3);
}

export function DeleteAnioLectivo(arg1) {
  return window['go']['services']['AcademicService']['DeleteAnioLectivo'](arg1);
}

export function GetAniosLectivos() {
  return window['go']['services']['AcademicService']['GetAniosLectivos']();
}

export function UpdateAnioFechas(arg1, arg2, arg3) {
  return window['go']['services']['AcademicService']['UpdateAnioFechas'](arg1, arg2, arg3);
}
