// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';

export function Login(arg1:string,arg2:string):Promise<dtos.UsuarioResponseDTO>;

export function Logout():Promise<void>;

export function ObtenerUsuarioSesion():Promise<dtos.UsuarioResponseDTO>;
