// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {faculty} from '../models';

export function ActualizarCurso(arg1:faculty.GuardarCursoDTO):Promise<void>;

export function CrearCurso(arg1:faculty.GuardarCursoDTO):Promise<void>;

export function EliminarCurso(arg1:number):Promise<void>;

export function GenerarCursosMasivos():Promise<string>;

export function ListarCursos(arg1:number):Promise<Array<faculty.CursoResponseDTO>>;
