// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarCurso(arg1) {
  return window['go']['services']['CourseService']['ActualizarCurso'](arg1);
}

export function CrearCurso(arg1) {
  return window['go']['services']['CourseService']['CrearCurso'](arg1);
}

export function EliminarCurso(arg1) {
  return window['go']['services']['CourseService']['EliminarCurso'](arg1);
}

export function ListarCursos(arg1) {
  return window['go']['services']['CourseService']['ListarCursos'](arg1);
}
