// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {faculty} from '../models';

export function AsignarDocenteMateria(arg1:faculty.AsignarDocenteDTO):Promise<void>;

export function EliminarAsignacion(arg1:number,arg2:number):Promise<void>;

export function ObtenerDistributivo(arg1:number):Promise<Array<faculty.ItemDistributivoDTO>>;
