// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AsignarDocenteMateria(arg1) {
  return window['go']['services']['DistributivoService']['AsignarDocenteMateria'](arg1);
}

export function EliminarAsignacion(arg1, arg2) {
  return window['go']['services']['DistributivoService']['EliminarAsignacion'](arg1, arg2);
}

export function ObtenerDistributivo(arg1) {
  return window['go']['services']['DistributivoService']['ObtenerDistributivo'](arg1);
}
