// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {enrollment} from '../models';
import {context} from '../models';

export function GuardarMatricula(arg1:enrollment.GuardarMatriculaDTO):Promise<enrollment.Matricula>;

export function LeerArchivoParaVista(arg1:string):Promise<string>;

export function ObtenerHistorial(arg1:number):Promise<Array<enrollment.HistorialMatriculaDTO>>;

export function ObtenerMatriculaActual(arg1:number):Promise<enrollment.MatriculaResponseDTO>;

export function RetirarEstudiante(arg1:number,arg2:string):Promise<void>;

export function SeleccionarArchivo(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
