// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GuardarMatricula(arg1) {
  return window['go']['services']['EnrollmentService']['GuardarMatricula'](arg1);
}

export function LeerArchivoParaVista(arg1) {
  return window['go']['services']['EnrollmentService']['LeerArchivoParaVista'](arg1);
}

export function ObtenerHistorial(arg1) {
  return window['go']['services']['EnrollmentService']['ObtenerHistorial'](arg1);
}

export function ObtenerMatriculaActual(arg1) {
  return window['go']['services']['EnrollmentService']['ObtenerMatriculaActual'](arg1);
}

export function RegistrarRetiroCompleto(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['EnrollmentService']['RegistrarRetiroCompleto'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RetirarEstudiante(arg1, arg2) {
  return window['go']['services']['EnrollmentService']['RetirarEstudiante'](arg1, arg2);
}

export function SeleccionarArchivo(arg1) {
  return window['go']['services']['EnrollmentService']['SeleccionarArchivo'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['EnrollmentService']['SetContext'](arg1);
}
