// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';

export function GuardarConfiguracion(arg1:dtos.ConfiguracionInstitucionalDTO):Promise<void>;

export function ObtenerConfiguracion():Promise<dtos.ConfiguracionInstitucionalDTO>;
