// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {management} from '../models';
import {context} from '../models';

export function ActualizarCita(arg1:management.ActualizarCitaDTO):Promise<management.Convocatoria>;

export function AgendarCita(arg1:management.AgendarCitaDTO):Promise<management.Convocatoria>;

export function EliminarCita(arg1:number):Promise<void>;

export function ListarCitas(arg1:management.FiltroCitasDTO):Promise<Array<management.CitaResumenDTO>>;

export function MarcarCompletada(arg1:number,arg2:boolean):Promise<void>;

export function ObtenerCita(arg1:number):Promise<management.CitaDetalleDTO>;

export function Startup(arg1:context.Context):Promise<void>;
