// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerarResumenAlertasCitas(arg1, arg2, arg3) {
  return window['go']['services']['NotificationsService']['GenerarResumenAlertasCitas'](arg1, arg2, arg3);
}

export function ListarNotificacionesPaginadas(arg1, arg2, arg3) {
  return window['go']['services']['NotificationsService']['ListarNotificacionesPaginadas'](arg1, arg2, arg3);
}

export function MarcarNotificacionLeida(arg1) {
  return window['go']['services']['NotificationsService']['MarcarNotificacionLeida'](arg1);
}

export function ResumenNotificaciones(arg1, arg2) {
  return window['go']['services']['NotificationsService']['ResumenNotificaciones'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['NotificationsService']['SetContext'](arg1);
}

export function StartScheduler() {
  return window['go']['services']['NotificationsService']['StartScheduler']();
}

export function StopScheduler() {
  return window['go']['services']['NotificationsService']['StopScheduler']();
}
