// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {notifications} from '../models';
import {dto} from '../models';
import {context} from '../models';

export function GenerarResumenAlertasCitas(arg1:string,arg2:string,arg3:time.Time):Promise<notifications.Notificacion>;

export function ListarNotificacionesPaginadas(arg1:string,arg2:number,arg3:number):Promise<dto.NotificacionesPaginadasDTO>;

export function MarcarNotificacionLeida(arg1:number):Promise<void>;

export function ResumenNotificaciones(arg1:string,arg2:number):Promise<dto.ResumenNotificacionesDTO>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartScheduler():Promise<void>;

export function StopScheduler():Promise<void>;
