// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarConfiguracion(arg1, arg2) {
  return window['go']['services']['SecurityConfigService']['ActualizarConfiguracion'](arg1, arg2);
}

export function ListarConfiguraciones() {
  return window['go']['services']['SecurityConfigService']['ListarConfiguraciones']();
}

export function ObtenerConfiguracion(arg1) {
  return window['go']['services']['SecurityConfigService']['ObtenerConfiguracion'](arg1);
}

export function VerificarClaveUsuario(arg1, arg2) {
  return window['go']['services']['SecurityConfigService']['VerificarClaveUsuario'](arg1, arg2);
}
