// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {security} from '../models';

export function ActualizarConfiguracion(arg1:string,arg2:boolean):Promise<void>;

export function ListarConfiguraciones():Promise<Array<security.ConfiguracionSeguridad>>;

export function ObtenerConfiguracion(arg1:string):Promise<boolean>;

export function VerificarClaveUsuario(arg1:number,arg2:string):Promise<boolean>;
