// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuscarEstudiantes(arg1) {
  return window['go']['services']['StudentService']['BuscarEstudiantes'](arg1);
}

export function EliminarFamiliar(arg1) {
  return window['go']['services']['StudentService']['EliminarFamiliar'](arg1);
}

export function GuardarDocumentoPDF(arg1, arg2, arg3) {
  return window['go']['services']['StudentService']['GuardarDocumentoPDF'](arg1, arg2, arg3);
}

export function GuardarEstudiante(arg1) {
  return window['go']['services']['StudentService']['GuardarEstudiante'](arg1);
}

export function GuardarFoto(arg1, arg2) {
  return window['go']['services']['StudentService']['GuardarFoto'](arg1, arg2);
}

export function GuardarFotoBase64(arg1, arg2, arg3) {
  return window['go']['services']['StudentService']['GuardarFotoBase64'](arg1, arg2, arg3);
}

export function ImportarEstudiantes(arg1) {
  return window['go']['services']['StudentService']['ImportarEstudiantes'](arg1);
}

export function ObtenerDocumentoPDF(arg1, arg2) {
  return window['go']['services']['StudentService']['ObtenerDocumentoPDF'](arg1, arg2);
}

export function ObtenerEstudiante(arg1) {
  return window['go']['services']['StudentService']['ObtenerEstudiante'](arg1);
}

export function ObtenerFotoBase64(arg1) {
  return window['go']['services']['StudentService']['ObtenerFotoBase64'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['StudentService']['SetContext'](arg1);
}
