// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {student} from '../models';

export function BuscarEstudiantes(arg1:string):Promise<Array<student.EstudianteListaDTO>>;

export function EliminarFamiliar(arg1:number):Promise<void>;

export function GuardarEstudiante(arg1:student.GuardarEstudianteDTO):Promise<student.Estudiante>;

export function GuardarFoto(arg1:number,arg2:string):Promise<string>;

export function GuardarFotoBase64(arg1:number,arg2:string,arg3:string):Promise<string>;

export function ObtenerEstudiante(arg1:number):Promise<student.Estudiante>;

export function ObtenerFotoBase64(arg1:number):Promise<string>;
