// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {faculty} from '../models';

export function ActualizarDocente(arg1:faculty.GuardarDocenteDTO):Promise<void>;

export function CrearDocente(arg1:faculty.GuardarDocenteDTO):Promise<void>;

export function ListarDocentes(arg1:boolean):Promise<Array<faculty.DocenteDTO>>;

export function ToggleEstado(arg1:number):Promise<void>;
