// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarDocente(arg1) {
  return window['go']['services']['TeacherService']['ActualizarDocente'](arg1);
}

export function CrearDocente(arg1) {
  return window['go']['services']['TeacherService']['CrearDocente'](arg1);
}

export function ListarDocentes(arg1) {
  return window['go']['services']['TeacherService']['ListarDocentes'](arg1);
}

export function ToggleEstado(arg1) {
  return window['go']['services']['TeacherService']['ToggleEstado'](arg1);
}
