// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {management} from '../models';
import {context} from '../models';

export function AbrirPlantillaEnEditor(arg1:number):Promise<void>;

export function ActualizarPlantilla(arg1:number,arg2:string,arg3:string):Promise<management.Plantilla>;

export function EliminarPlantilla(arg1:number):Promise<void>;

export function GenerarCertificado(arg1:number,arg2:number,arg3:Record<string, string>):Promise<string>;

export function ListarPlantillas():Promise<Array<management.Plantilla>>;

export function ObtenerDatosCertificado(arg1:number,arg2:number):Promise<Record<string, string>>;

export function RecargarTagsPlantilla(arg1:number):Promise<management.Plantilla>;

export function ReemplazarArchivoPlantilla(arg1:number):Promise<management.Plantilla>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SubirPlantilla(arg1:string,arg2:string):Promise<management.Plantilla>;
