// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirPlantillaEnEditor(arg1) {
  return window['go']['services']['TemplateService']['AbrirPlantillaEnEditor'](arg1);
}

export function ActualizarPlantilla(arg1, arg2, arg3) {
  return window['go']['services']['TemplateService']['ActualizarPlantilla'](arg1, arg2, arg3);
}

export function ActualizarTagLabels(arg1, arg2) {
  return window['go']['services']['TemplateService']['ActualizarTagLabels'](arg1, arg2);
}

export function EliminarPlantilla(arg1) {
  return window['go']['services']['TemplateService']['EliminarPlantilla'](arg1);
}

export function GenerarCertificado(arg1, arg2, arg3) {
  return window['go']['services']['TemplateService']['GenerarCertificado'](arg1, arg2, arg3);
}

export function ListarPlantillas() {
  return window['go']['services']['TemplateService']['ListarPlantillas']();
}

export function ObtenerDatosCertificado(arg1, arg2) {
  return window['go']['services']['TemplateService']['ObtenerDatosCertificado'](arg1, arg2);
}

export function ObtenerFirmaBase64() {
  return window['go']['services']['TemplateService']['ObtenerFirmaBase64']();
}

export function RecargarTagsPlantilla(arg1) {
  return window['go']['services']['TemplateService']['RecargarTagsPlantilla'](arg1);
}

export function ReemplazarArchivoPlantilla(arg1) {
  return window['go']['services']['TemplateService']['ReemplazarArchivoPlantilla'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['TemplateService']['SetContext'](arg1);
}

export function SubirFirma() {
  return window['go']['services']['TemplateService']['SubirFirma']();
}

export function SubirPlantilla(arg1, arg2) {
  return window['go']['services']['TemplateService']['SubirPlantilla'](arg1, arg2);
}

export function TieneFirma() {
  return window['go']['services']['TemplateService']['TieneFirma']();
}

export function ToggleIncluyeFirma(arg1, arg2) {
  return window['go']['services']['TemplateService']['ToggleIncluyeFirma'](arg1, arg2);
}
