// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {context} from '../models';

export function ActualizarUsuario(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CambiarMiClave(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ListarUsuarios():Promise<Array<dtos.UsuarioResponseDTO>>;

export function ObtenerFotoPerfilBase64(arg1:number):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SubirFotoPerfil(arg1:number):Promise<string>;
