// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarUsuario(arg1, arg2, arg3, arg4) {
  return window['go']['services']['UserService']['ActualizarUsuario'](arg1, arg2, arg3, arg4);
}

export function CambiarMiClave(arg1, arg2, arg3) {
  return window['go']['services']['UserService']['CambiarMiClave'](arg1, arg2, arg3);
}

export function ListarUsuarios() {
  return window['go']['services']['UserService']['ListarUsuarios']();
}

export function ObtenerFotoPerfilBase64(arg1) {
  return window['go']['services']['UserService']['ObtenerFotoPerfilBase64'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['UserService']['SetContext'](arg1);
}

export function SubirFotoPerfil(arg1) {
  return window['go']['services']['UserService']['SubirFotoPerfil'](arg1);
}
