// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';

export function ActualizarUsuario(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CambiarMiClave(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ListarUsuarios():Promise<Array<dtos.UsuarioResponseDTO>>;
