// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<main.UpdateCheckResult>;

export function DoUpdate():Promise<string>;

export function RestartApp():Promise<void>;
